### ISSUE TITLE
Can't get usage with 'opagetvf_env -h' or 'opagetvf_env --help'

### ISSUE THREAD

**Issue by ghost** [intel/opa-ff#5]
hi,

There is a manpage file for opagetvf_env, but can't get usage with 'opagetvf_env -h' or 'opagetvf_env --help'.

[root@rdma-qe-15 ~]$ opagetvf_env
[root@rdma-qe-15 ~]$ echo $?
0
[root@rdma-qe-15 ~]$ 
[root@rdma-qe-15 ~]$ /usr/sbin/opagetvf_env --help
[root@rdma-qe-15 ~]$ /usr/sbin/opagetvf_env -h
[root@rdma-qe-15 ~]$ echo $?
0
[root@rdma-qe-15 ~]$ man /usr/share/man/man1/opagetvf_env.1.gz | wc 
     21      59     645

**Comment by ToddRimmer** [comment]
This is the expected behavior, this script is designed to be “dot included” in other scripts.  As such it does not parse $\* so that it will not impact the script it is installed in.

Todd Rimmer
DCSG Architecture
Voice: 610-312-2152     Fax: 610-312-2233
Todd.Rimmer@intel.commailto:Todd.Rimmer@intel.com

**Comment by ghost** [comment]
Thanks for the explanation.
